engines:
  eslint:
    enabled: true
    channel: 'eslint-3'
    config: .eslintrc.yml
  duplication:
    enabled: true
    config:
      languages:
        - javascript

ratings:
  paths:
    - '**.js'
