engines:
  eslint:
    enabled: true
    channel: 'eslint-3'
    config: .eslintrc.yml
    checks:
      class-methods-use-this:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript

ratings:
  paths:
    - '**.js'

exclude_paths:
  - 'test/'
